### ISSUE TITLE
Lampiran foto untuk TLO

### ISSUE THREAD

**Issue by agilma** [ThunderID/GANTIRUGI-MAINTENANCE#10]
**Tuliskan Error/Bug**
tambahkan lampiran foto untuk Polis TLO

**Platform / Aplikasi yang bermasalah:**
Mobile Apps

**Hasil yang diharapkan**
ada fitur tambah foto untuk Polis TLO

**Catatan**
Lampiran Foto adalah STNK dan KTP yang wajib ada, namun untuk foto kendaraan sifatnya OPTIONAL, bisa diisi. Saat ini foto tidak bisa dilampirkan dalam Surat Penawaran

**Comment by chelsymooy** [comment]
Dibuka untuk Gantirugi Mobil   & niaga
