### ISSUE TITLE
Obyek Pertanggungan Mobile Niaga

### ISSUE THREAD

**Issue by agilma** [ThunderID/GANTIRUGI-MAINTENANCE#15]
**Tuliskan Error/Bug**
(instead of Pickup) dalam **Surat Penawaran**, **Surat Permohonan**, dan **Ikhtisar Perlidungan**

**Catatan**
File terlampir

**Comment by chelsymooy** [comment]
Tidak dieksekusi karena obj pertanggungan mengikuti kelas kendaraan
