### ISSUE TITLE
Email notie Judul email harusnya ada Merk, Type Mobile

### ISSUE THREAD

**Issue by agilma** [ThunderID/GANTIRUGI-MAINTENANCE#24]
**Tuliskan Error/Bug**
untuk judul email harus ada Merk/Make dan Type Mobil

**Hasil yang diharapkan**
Gunakan **SUZUKI CARRY** ... dan jangan hanya **SUZUKI** saja atau lebih detail seperti **SUZUKI CARRY PICK UP Flat Deck Gen-11**

**Comment by rahmanhasibuan** [comment]
Belum sesuai dengan hasil yang diharapkan, Masih menggunakan Merk saja dan belum lengkap
